Update ReactiveLoggerService.cs
 error CS1061: 'RXAction' does not contain a definition for 'HasAnyFlag' and no accessible extension method 'HasAnyFlag' accepting a first argument of type 'RXAction' could be found (are you missing a using directive or an assembly reference?)